variable "project_name" {}
variable "database_name" {}
variable "database_username" {}
variable "database_password" {}
variable "database_engine" {}
variable "database_engine_version" {}
variable "database_instance_class" {}
variable "database_sg_id" {}
variable "parameter_groupname" {}